version: "3.7"
services: 
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  redis:
    image: redis:alpine

  api:
    build: 
      dockerfile: API/Dockerfile
    ports:
      - 7000:7000

  microservice1:
    build: 
      dockerfile: MS1/Dockerfile
    ports:
      - 7001:7001
    
  microservice2:
    build:
      dockerfile: MS2/Dockerfile
    ports:
      - 7002:7002

