version: "3.7"
networks:
  network-service:
    driver: bridge
    name: network-internal
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    networks:
      network-service:
        ipv4_address: 10.5.0.10

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: potgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data 
    networks:
      network-service:
        ipv4_address: 10.5.0.11
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: patrickbpiccini@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      network-service:
        ipv4_address: 10.5.0.12

  redis:
    image: redis:alpine
    networks:
      network-service:
        ipv4_address: 10.5.0.9

