version: "3.7"
services: 
  microservice1:
    image: python:3.8-alpine
    command: 
      - pip install -r requeriments.txt
      - python /app/rabbit_recive/recive_queue.py
    ports:
      - 7000:7000
    working_dir: /app
    volumes: 
        - ./MS1:/home/opc/app
    # volumes: 
    #   - ./app:f\Usuários\Patrick\Documents\@Codigos\Portifoleo\MS-aplication\
    
  microservice2:
    image: python:3.8-alpine
    command: 
      - pip install -r requeriments.txt
      - python /app/rabbit_recive/recive_queue.py
    ports:
      - 7001:7001
    working_dir: /app
    volumes: 
      - ./MS2:/home/opc/app
    # volumes: 
    #   - ./app:f\Usuários\Patrick\Documents\@Codigos\Portifoleo\MS-aplication\

  api:
    image: python:3.8-alpine
    command: 
      - pip install -r requeriments.txt
      - python /app/server.py
    ports:
      - 7001:7001
    working_dir: /app
    volumes: 
      - ./MS2:/home/opc/app
    # volumes: 
    #   - ./app:f\Usuários\Patrick\Documents\@Codigos\Portifoleo\MS-aplication\

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  redis:
    image: redis:alpine
    