version: "3.7"
services: 
  microservice_1:
    image: python:3.8-alpine
    command: pip install -r requeriments.txt
    ports:
      - 7000:7000
    working_dir: /app
    #volume: ./:/app1
    volumes: 
      - ./app:f\Usuários\Patrick\Documents\@Codigos\Portifoleo\MS-aplication\app1
    
  microservice_2:
    image: python:3.8-alpine
    command: pip install -r requeriments.txt
    ports:
      - 7001:7001
    working_dir: /app
    #volume: ./:/app2
    volumes: 
      - ./app:f\Usuários\Patrick\Documents\@Codigos\Portifoleo\MS-aplication\app2

  redis:
    image: redis:alpine
    