version: "3.7"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "5672"
    labels:
      NAME: "rabbitmq1"
    networks:
      network-service:
        ipv4_address: 10.5.0.10

  redis:
    image: redis:alpine
    networks:
      network-service:
        ipv4_address: 10.5.0.9

networks:
  network-service:
    name: network-internal
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
        - gateway: 10.5.0.1