version: "3.7"
services:
  api:
    build:
      dockerfile: API/Dockerfile
    ports:
      - 7000:7000
    networks:
      - network-application

  microservice1:
    build:
      dockerfile: MS1/Dockerfile
    ports:
      - 7001:7001
    networks:
      - network-application

  microservice2:
    build:
      dockerfile: MS2/Dockerfile
    ports:
      - 7002:7002
    networks:
      - network-application

networks:
    network-application:
        external:
            name: network-internal