version: "3.7"
services:
  api:
    build:
      dockerfile: API/Dockerfile
    ports:
      - "7000:7000"
    networks:
      - network-internal

  microservice1:
    build:
      dockerfile: MS1/Dockerfile
    ports:
      - "7001:7001"
    networks:
      - network-internal

  microservice2:
    build:
      dockerfile: MS2/Dockerfile
    ports:
      - "7002:7002"
    networks:
      - network-internal

networks:
    network-internal:
        external: true