version: "3.7"
services: 
  microservice1:
    build: /API/dockerfile
    ports:
      - 7001:7001
    working_dir: /app
    
  microservice2:
    build: /MS1/dockerfile
    ports:
      - 7002:7002
    working_dir: /app

  api:
    build: /MS2/dockerfile
    ports:
      - 7000:7000

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  redis:
    image: redis:alpine
    